import nkzw from "@nkzw/oxlint-config";
import { defineConfig } from "oxlint";

// oxlint-disable-next-line import/no-default-export
export default defineConfig({
	categories: {
		correctness: "error",
	},
	env: {
		browser: true,
		es6: true,
		node: true,
	},
	extends: [nkzw],
	globals: {
		__DEV__: "readonly",
		jest: "readonly",
	},
	ignorePatterns: [
		"AGENTS.md",
		".agent/**",
		".agents",
		".agents/**",
		".claude/**",
		".codex/**",
		".continue/**",
		".cursor/**",
		".expect/**",
		".gemini/**",
		".github/skills",
		".github/skills/**",
		".impeccable/**",
		".opencode/**",
		".pi/**",
		".playwright-mcp/**",
		".roo/**",
		".windsurf/**",
		"tools/oxlint/anti-slop/**",
		"packages/documents/src/viewer/**",
		"**/node_modules",
		"**/.next",
		"**/build",
		"**/dist",
		"**/.dist",
		"**/.react-email",
		"**/.turbo",
		"**/.vercel",
		"**/.workflow-data",
		"**/.well-known/workflow",
		"**/.vscode",
		"**/packages/db/src/db",
		"**/lint-staged.config.js",
		"**/.cursorrules",
		"**/expo-env.d.ts",
		"**/ios",
		"**/android",
		"**/.expo",
		"**/.expo-shared",
		"**/metro-cache",
		"**/coverage",
		"**/.cache",
		"**/storybook-static",
		"**/.husky",
		"**/.trigger",
		"**/*.min.js",
		"**/*.d.ts",
		"**/next-env.d.ts",
		"**/postcss.config.*",
		"**/bun.lockb",
		"**/*.lock",
		"skills-lock.json",
		"**/.git",
		"**/tmp",
		"**/.docker",
		"**/containers",
		"**/.claude",
	],
	jsPlugins: [
		"@shadcn/lint",
		{
			name: "github",
			specifier: "eslint-plugin-github",
		},
		{
			name: "starter",
			specifier: "./tools/oxlint/starter/index.js",
		},
		{
			name: "anti-slop",
			specifier: "./tools/oxlint/anti-slop/index.ts",
		},
		{
			name: "unicorn-js",
			specifier: "eslint-plugin-unicorn",
		},
	],
	overrides: [
		{
			files: ["packages/ui/src/components/**"],
			rules: {
				"shadcn/no-restyle": "off",
				"shadcn/require-static-classes": "off",
			},
		},
		{
			files: ["globalSetup.ts", "redisGlobalSetup.ts", "packages/infinite-website/scripts/**/*.{js,ts}"],
			rules: {
				"no-console": "off",
			},
		},
		{
			files: [
				"packages/infinite-website/src/behavior/compile-expression.ts",
				"packages/infinite-website/src/behavior/contracts.ts",
			],
			rules: {
				"unicorn/no-thenable": "off",
			},
		},
		{
			files: [
				"packages/server/src/services/chat.ts",
				"packages/server/tests/services/website-generation.test.ts",
			],
			rules: {
				"unicorn/prefer-structured-clone": "off",
			},
		},
		{
			files: ["packages/ui/src/components/drawer.tsx"],
			rules: {
				"react/button-has-type": "off",
			},
		},
		{
			files: ["packages/ui/src/lib/utils.ts"],
			rules: {
				"import/export": "off",
			},
		},
		{
			files: ["tools/oxlint/starter/**/*.js"],
			rules: {
				"import/no-default-export": "off",
			},
		},
		{
			files: [
				"tailwind.config.ts",
				"next.config.ts",
				"**/vitest.config.*",
				"**/page.{js,jsx,ts,tsx}",
				"**/layout.{js,jsx,ts,tsx}",
				"**/not-found.{js,jsx,ts,tsx}",
				"**/error.{js,jsx,ts,tsx}",
				"**/global-error.{js,jsx,ts,tsx}",
				"**/loading.{js,jsx,ts,tsx}",
				"**/robots.{js,jsx,ts,tsx}",
				"**/sitemap.{js,jsx,ts,tsx}",
				"**/middleware.{js,jsx,ts,tsx}",
				"**/proxy.{js,jsx,ts,tsx}",
				"**/i18n/request.ts",
				"**/eslint**",
				"**/drizzle.config.ts",
			],
			rules: {
				"import/no-default-export": "off",
			},
		},
		{
			files: ["packages/server/src/**/*.{ts,tsx}"],
			rules: {
				"import/no-cycle": ["error", { allowUnsafeDynamicCyclicDependency: true }],
			},
		},
		{
			files: ["**/*.test.{js,jsx,ts,tsx}", "**/*.spec.{js,jsx,ts,tsx}", "**/tests/**/*.{js,jsx,ts,tsx}"],
			rules: {
				complexity: "off",
				"max-depth": "off",
				"max-lines": "off",
				"max-lines-per-function": "off",
				"max-params": "off",
				"vitest/require-mock-type-parameters": "off",
			},
		},
		{
			files: ["packages/email/src/emails/**/*.{js,jsx,ts,tsx}"],
			rules: {
				"import/no-default-export": "off",
			},
		},
		{
			files: ["**/*.stories.{js,jsx,ts,tsx}", "**/.storybook/**/*.{js,jsx,ts,tsx}"],
			rules: {
				"import/no-default-export": "off",
			},
		},
		{
			files: ["packages/infinite-website/**/*.{js,jsx,ts,tsx}"],
			rules: {
				"max-lines": "off",
			},
		},
		{
			files: ["packages/infinite-website/src/templates/*/index.ts"],
			rules: {
				"perfectionist/sort-objects": "off",
			},
		},
		{
			files: ["apps/webapp/**/*.{js,jsx,ts,tsx}"],
			plugins: ["eslint", "oxc", "typescript", "react", "import", "vitest", "promise", "nextjs"],
			rules: {
				"nextjs/google-font-display": "error",
				"nextjs/no-duplicate-head": "error",
				"nextjs/no-html-link-for-pages": "error",
				"nextjs/no-img-element": "error",
				"nextjs/no-sync-scripts": "error",
				"nextjs/no-title-in-document-head": "error",
			},
		},
	],
	plugins: ["eslint", "oxc", "typescript", "react", "import", "vitest", "promise"],
	rules: {
		"@nkzw/no-instanceof": "off",
		"anti-slop/no-array-filter-map": "error",
		"anti-slop/no-chained-type-assertions": "error",
		"anti-slop/no-comments": "error",
		"anti-slop/no-conditional-empty-object-spread": "error",
		"anti-slop/no-css-modules": "error",
		"anti-slop/no-explicit-function-return-type": "off",
		"anti-slop/no-known-value-widening": "error",
		"anti-slop/no-let": "error",
		"anti-slop/no-module-mocking": "off",
		"anti-slop/no-object-parameters": "error",
		"anti-slop/no-reduce-accumulator-copy": "error",
		"anti-slop/no-reflect-apply": "error",
		"anti-slop/no-reflect-get": "error",
		"anti-slop/no-runtime-typeof": "error",
		"anti-slop/no-shape-in-symbol-names": "error",
		"anti-slop/no-tautological-absence": "error",
		"anti-slop/no-unknown-parameters": "error",
		"anti-slop/no-unknown-returns": "error",
		"anti-slop/no-unknown-type-aliases": "error",
		"anti-slop/no-unsafe-dictionary-type": "error",
		"anti-slop/no-widen-then-assert": "error",
		"anti-slop/require-readable-spacing": "error",
		"anti-slop/require-safety-comment-for-type-assertion": "error",
		complexity: ["error", 26],
		"func-style": ["error", "expression", { allowArrowFunctions: true }],
		"github/no-then": "error",
		"import/no-default-export": "error",
		"import/no-namespace": "off",
		"max-depth": ["error", 3],
		"max-lines": ["error", { max: 720, skipBlankLines: true }],
		"max-lines-per-function": ["error", { max: 215, skipBlankLines: true }],
		"max-params": ["error", 5],
		"no-console": ["error", { allow: ["error", "warn"] }],
		"no-empty": ["error", { allowEmptyCatch: true }],
		"no-loop-func": "error",
		"no-nested-ternary": "error",
		"no-unused-expressions": "off",
		"no-unused-vars": [
			"error",
			{
				argsIgnorePattern: "^_",
				caughtErrorsIgnorePattern: "^_",
				varsIgnorePattern: "^_",
			},
		],
		"promise/no-callback-in-promise": "off",
		"promise/no-nesting": "error",
		"promise/no-new-statics": "off",
		"promise/prefer-await-to-then": "error",
		"promise/valid-params": "off",
		"react/display-name": "warn",
		"react/exhaustive-deps": "error",
		"react/jsx-key": "error",
		"react/no-unescaped-entities": "error",
		"react/no-unstable-nested-components": "error",
		"react/rules-of-hooks": "error",
		"react/self-closing-comp": "error",
		"shadcn/no-restyle": ["error", { allow: ["layout"] }],
		"shadcn/require-static-classes": "error",
		"starter/padding-around-multiline-statements": "off",
		"typescript/consistent-type-assertions": ["error", { assertionStyle: "never" }],
		"typescript/consistent-type-definitions": ["error", "type"],
		"typescript/no-explicit-any": "warn",
		"unicorn-js/no-for-loop": "error",
		"unicorn/consistent-function-scoping": "off",
	},
	settings: {
		next: {
			rootDir: "apps/webapp",
		},
		react: {
			version: "19.2.8",
		},
		shadcn: {
			note: "Use shared variants. Styling exceptions require individual user approval; do not suppress findings or widen contracts without approval.",
			ui: "@starter/ui/components",
		},
	},
});
