import { brandFontCatalogAdditions } from "./catalog-additions";

export const brandFontCatalogVersion = 1 as const;

type BrandFontAxis = {
	default: number;
	max: number;
	min: number;
};

export type BrandFontCatalogEntry = {
	axes: Readonly<Record<string, BrandFontAxis>>;
	fallback: string;
	family: string;
	italic?: boolean;
	scripts: ReadonlyArray<string>;
	staticWeights?: ReadonlyArray<number>;
	weight: BrandFontAxis;
};

export const brandFontCatalog = {
	alegreya: {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Alegreya Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 400 },
	},
	"alegreya-sans": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Alegreya Sans",
		scripts: ["Latn"],
		staticWeights: [100, 300, 400, 500, 700, 800, 900],
		weight: { default: 400, max: 900, min: 100 },
	},
	"anonymous-pro": {
		axes: {},
		fallback: "ui-monospace, SFMono-Regular, Menlo, monospace",
		family: "Anonymous Pro",
		scripts: ["Latn"],
		staticWeights: [400, 700],
		weight: { default: 400, max: 700, min: 400 },
	},
	"archivo-narrow": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Archivo Narrow Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 700, min: 400 },
	},
	arvo: {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Arvo",
		scripts: ["Latn"],
		staticWeights: [400, 700],
		weight: { default: 400, max: 700, min: 400 },
	},
	cabin: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Cabin Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 700, min: 400 },
	},
	cairo: {
		axes: {},
		fallback: "Tahoma, Arial, sans-serif",
		family: "Cairo Variable",
		scripts: ["Arab", "Latn"],
		weight: { default: 400, max: 1000, min: 200 },
	},
	cardo: {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Cardo",
		scripts: ["Latn"],
		staticWeights: [400, 700],
		weight: { default: 400, max: 700, min: 400 },
	},
	chivo: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Chivo Variable",
		italic: true,
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	"crimson-pro": {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Crimson Pro Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 200 },
	},
	"crimson-text": {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Crimson Text",
		scripts: ["Latn"],
		staticWeights: [400, 600, 700],
		weight: { default: 400, max: 700, min: 400 },
	},
	"dm-sans": {
		axes: { opsz: { default: 14, max: 40, min: 9 } },
		fallback: "system-ui, sans-serif",
		family: "DM Sans Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 1000, min: 100 },
	},
	figtree: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Figtree Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 300 },
	},
	geist: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Geist Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	"ibm-plex-sans": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "IBM Plex Sans Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 700, min: 100 },
	},
	inter: {
		axes: { opsz: { default: 14, max: 32, min: 14 } },
		fallback: "system-ui, sans-serif",
		family: "Inter Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	"josefin-sans": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Josefin Sans Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 700, min: 100 },
	},
	jost: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Jost Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	karla: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Karla Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 800, min: 200 },
	},
	lato: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Lato",
		italic: true,
		scripts: ["Latn"],
		staticWeights: [100, 300, 400, 700, 900],
		weight: { default: 400, max: 900, min: 100 },
	},
	"libre-baskerville": {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Libre Baskerville Variable",
		italic: true,
		scripts: ["Latn"],
		weight: { default: 400, max: 700, min: 400 },
	},
	"libre-franklin": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Libre Franklin Variable",
		italic: true,
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	literata: {
		axes: { opsz: { default: 14, max: 72, min: 7 } },
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Literata Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 200 },
	},
	lora: {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Lora Variable",
		italic: true,
		scripts: ["Latn"],
		weight: { default: 400, max: 700, min: 400 },
	},
	manrope: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Manrope Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 800, min: 200 },
	},
	"maven-pro": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Maven Pro Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 400 },
	},
	merriweather: {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Merriweather Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 300 },
	},
	montserrat: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Montserrat Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	mulish: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Mulish Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 1000, min: 200 },
	},
	neuton: {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Neuton",
		scripts: ["Latn"],
		staticWeights: [200, 300, 400, 700, 800],
		weight: { default: 400, max: 800, min: 200 },
	},
	newsreader: {
		axes: { opsz: { default: 16, max: 72, min: 6 } },
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Newsreader Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 800, min: 200 },
	},
	"noto-kufi-arabic": {
		axes: {},
		fallback: "Tahoma, Arial, sans-serif",
		family: "Noto Kufi Arabic Variable",
		scripts: ["Arab", "Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	"noto-naskh-arabic": {
		axes: {},
		fallback: "Tahoma, Arial, serif",
		family: "Noto Naskh Arabic Variable",
		scripts: ["Arab", "Latn"],
		weight: { default: 400, max: 700, min: 400 },
	},
	"noto-sans": {
		axes: { wdth: { default: 100, max: 100, min: 62.5 } },
		fallback: "system-ui, sans-serif",
		family: "Noto Sans Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	"noto-sans-arabic": {
		axes: { wdth: { default: 100, max: 100, min: 62.5 } },
		fallback: "Tahoma, Arial, sans-serif",
		family: "Noto Sans Arabic Variable",
		scripts: ["Arab", "Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	"open-sans": {
		axes: { wdth: { default: 100, max: 100, min: 75 } },
		fallback: "system-ui, sans-serif",
		family: "Open Sans Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 800, min: 300 },
	},
	outfit: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Outfit Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	platypi: {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Platypi Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 800, min: 300 },
	},
	"playfair-display": {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Playfair Display Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 400 },
	},
	poppins: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Poppins",
		italic: true,
		scripts: ["Latn"],
		staticWeights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
		weight: { default: 400, max: 900, min: 100 },
	},
	"proza-libre": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Proza Libre",
		scripts: ["Latn"],
		staticWeights: [400, 500, 600, 700, 800],
		weight: { default: 400, max: 800, min: 400 },
	},
	"pt-sans": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "PT Sans",
		scripts: ["Latn"],
		staticWeights: [400, 700],
		weight: { default: 400, max: 700, min: 400 },
	},
	"pt-serif": {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "PT Serif",
		italic: true,
		scripts: ["Latn"],
		staticWeights: [400, 700],
		weight: { default: 400, max: 700, min: 400 },
	},
	"public-sans": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Public Sans Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	raleway: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Raleway Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	roboto: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Roboto Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	"roboto-mono": {
		axes: {},
		fallback: "ui-monospace, SFMono-Regular, Menlo, monospace",
		family: "Roboto Mono Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 700, min: 100 },
	},
	"roboto-serif": {
		axes: { opsz: { default: 14, max: 144, min: 8 }, wdth: { default: 100, max: 150, min: 50 } },
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Roboto Serif Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	"roboto-slab": {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Roboto Slab Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	rubik: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Rubik Variable",
		italic: true,
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 300 },
	},
	"source-sans-3": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Source Sans 3 Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 200 },
	},
	"source-serif-4": {
		axes: { opsz: { default: 14, max: 60, min: 8 } },
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Source Serif 4 Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 200 },
	},
	"space-mono": {
		axes: {},
		fallback: "ui-monospace, SFMono-Regular, Menlo, monospace",
		family: "Space Mono",
		italic: true,
		scripts: ["Latn"],
		staticWeights: [400, 700],
		weight: { default: 400, max: 700, min: 400 },
	},
	spectral: {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Spectral",
		scripts: ["Latn"],
		staticWeights: [200, 300, 400, 500, 600, 700, 800],
		weight: { default: 400, max: 800, min: 200 },
	},
	syne: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Syne Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 800, min: 400 },
	},
	"varela-round": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Varela Round",
		scripts: ["Latn"],
		staticWeights: [400],
		weight: { default: 400, max: 400, min: 400 },
	},
	vollkorn: {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Vollkorn Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 400 },
	},
	"work-sans": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Work Sans Variable",
		italic: true,
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},

	...brandFontCatalogAdditions,
} as const satisfies Record<string, BrandFontCatalogEntry>;

export type BrandFontId = keyof typeof brandFontCatalog;

const brandFontById = new Map<string, BrandFontCatalogEntry>(Object.entries(brandFontCatalog));

export const getBrandFont = ({ fontId }: { fontId: string }) => {
	return brandFontById.get(fontId);
};
