export const brandFontCatalogAdditions = {
	"albert-sans": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Albert Sans Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	anybody: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Anybody Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	archivo: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Archivo Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	asap: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Asap Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	"atkinson-hyperlegible-next": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Atkinson Hyperlegible Next Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 800, min: 200 },
	},
	barlow: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Barlow",
		scripts: ["Latn"],
		staticWeights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
		weight: { default: 400, max: 900, min: 100 },
	},
	"be-vietnam-pro": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Be Vietnam Pro",
		scripts: ["Latn"],
		staticWeights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
		weight: { default: 400, max: 900, min: 100 },
	},
	bitter: {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Bitter Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	"bricolage-grotesque": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Bricolage Grotesque Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 800, min: 200 },
	},
	commissioner: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Commissioner Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	"familjen-grotesk": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Familjen Grotesk Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 700, min: 400 },
	},
	"frank-ruhl-libre": {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Frank Ruhl Libre Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 300 },
	},
	fraunces: {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Fraunces Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	fredoka: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Fredoka Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 700, min: 300 },
	},
	"funnel-display": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Funnel Display Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 800, min: 300 },
	},
	gabarito: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Gabarito Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 400 },
	},
	"google-sans-flex": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Google Sans Flex Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 1000, min: 1 },
	},
	grandstander: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Grandstander Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	"hanken-grotesk": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Hanken Grotesk Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	"ibm-plex-serif": {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "IBM Plex Serif",
		scripts: ["Latn"],
		staticWeights: [100, 200, 300, 400, 500, 600, 700],
		weight: { default: 400, max: 700, min: 100 },
	},
	"instrument-serif": {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Instrument Serif",
		scripts: ["Latn"],
		staticWeights: [400],
		weight: { default: 400, max: 400, min: 400 },
	},
	lexend: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Lexend Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	"libre-bodoni": {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Libre Bodoni Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 700, min: 400 },
	},
	"montagu-slab": {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Montagu Slab Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 700, min: 100 },
	},
	"noto-serif": {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Noto Serif Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	nunito: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Nunito Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 1000, min: 200 },
	},
	"nunito-sans": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Nunito Sans Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 1000, min: 200 },
	},
	onest: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Onest Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	oswald: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Oswald Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 700, min: 200 },
	},
	petrona: {
		axes: {},
		fallback: "Georgia, 'Times New Roman', serif",
		family: "Petrona Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 100 },
	},
	"playpen-sans": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Playpen Sans Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 800, min: 100 },
	},
	"plus-jakarta-sans": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Plus Jakarta Sans Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 800, min: 200 },
	},
	quicksand: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Quicksand Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 700, min: 300 },
	},
	"red-hat-display": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Red Hat Display Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 300 },
	},
	"rethink-sans": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Rethink Sans Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 800, min: 400 },
	},
	"schibsted-grotesk": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Schibsted Grotesk Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 400 },
	},
	signika: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Signika Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 700, min: 300 },
	},
	"sofia-sans": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Sofia Sans Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 1000, min: 1 },
	},
	"sofia-sans-condensed": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Sofia Sans Condensed Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 1000, min: 1 },
	},
	sora: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Sora Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 800, min: 100 },
	},
	"space-grotesk": {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Space Grotesk Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 700, min: 300 },
	},
	unbounded: {
		axes: {},
		fallback: "system-ui, sans-serif",
		family: "Unbounded Variable",
		scripts: ["Latn"],
		weight: { default: 400, max: 900, min: 200 },
	},
} as const;
