import type { BrandFontPairingId, BrandTypeScale } from "./pairings";

const lightDisplayHeadings: BrandTypeScale = {
	"display-lg": { weight: 300 },
	"display-md": { weight: 300 },
	"display-sm": { weight: 300 },
	"heading-lg": { brandFont: true, weight: 300 },
	"heading-md": { brandFont: true, weight: 300 },
	"heading-sm": { brandFont: true, weight: 300 },
};

export const brandFontPairingScales = {
	"albert-sans": {},
	"anybody-frank-ruhl-libre": {},
	"archivo-alegreya": { "display-lg": { weight: 800 }, "display-md": { weight: 700 }, "display-sm": { weight: 700 } },
	"bitter-nunito-sans": {},
	"bricolage-grotesque": {},
	"crimson-pro": {},
	default: {},
	"dm-sans-extralight": {
		"body-lg": { weight: 200 },
		"body-lg-em": { weight: 300 },
		"body-md": { weight: 200 },
		"body-md-em": { weight: 300 },
		"body-sm": { weight: 200 },
		"body-sm-em": { weight: 300 },
		"body-xs": { weight: 200 },
		"body-xs-em": { weight: 300 },
		code: { weight: 200 },
		"display-2xl": { weight: 200 },
		"display-lg": { weight: 200 },
		"display-md": { weight: 200 },
		"display-sm": { weight: 200 },
		"display-xl": { weight: 200 },
		"display-xs": { weight: 200 },
		"heading-lg": { weight: 200 },
		"heading-md": { weight: 200 },
		"heading-sm": { weight: 200 },
		"heading-xs": { weight: 200 },
		"label-lg": { weight: 200 },
		"label-md": { weight: 200 },
		"label-sm": { weight: 200 },
		"title-lg": { weight: 200 },
		"title-md": { weight: 200 },
		"title-sm": { weight: 200 },
		"title-xs": { weight: 200 },
		watermark: { weight: 200 },
	},
	editorial: {},
	"elegant-serif": {},
	"familjen-grotesk-be-vietnam-pro": {},
	figtree: {},
	"fraunces-open-sans": {},
	"fraunces-open-sans-thin": {
		"body-lg": { lineHeight: 1.35, weight: 300 },
		"body-md": { lineHeight: 1.35, weight: 300 },
		"display-lg": { tracking: "-0.025em", weight: 100 },
		"display-md": { tracking: "-0.025em", weight: 100 },
		"display-sm": { weight: 100 },
		"display-xs": { lineHeight: 1.15, weight: 100 },
		"heading-lg": { brandFont: true, lineHeight: 1.15, tracking: "0em", weight: 100 },
		"heading-md": { brandFont: true, weight: 100 },
		"heading-sm": { brandFont: true, weight: 100 },
		"heading-xs": { brandFont: true, weight: 100 },
		watermark: { weight: 300 },
	},
	"fredoka-quicksand": { "display-lg": { weight: 600 } },
	"funnel-display-onest": {},
	"gabarito-atkinson-hyperlegible-next": {},
	"google-sans-flex": {},
	"ibm-plex-serif-inter": {
		"display-lg": { weight: 400 },
		"display-md": { weight: 400 },
		"display-sm": { weight: 400 },
	},
	"instrument-serif-inter": {
		"display-lg": { weight: 400 },
		"display-md": { weight: 400 },
		"display-sm": { weight: 400 },
		"heading-lg": { brandFont: true, weight: 300 },
		"heading-md": { brandFont: true, weight: 300 },
		"heading-sm": { brandFont: true, weight: 300 },
	},
	"josefin-sans-karla": { "display-lg": { weight: 600 } },
	lexend: {},
	"libre-baskerville": {},
	"libre-bodoni-chivo": {},
	"literata-noto-sans": {},
	"manrope-lora": { "display-lg": { weight: 800 }, "display-md": { weight: 700 }, "display-sm": { weight: 700 } },
	minimal: {},
	modern: {},
	"modern-durable": {
		"display-lg": { tracking: "-0.05em", weight: 800 },
		"display-md": { tracking: "-0.05em", weight: 800 },
		"display-sm": { tracking: "-0.025em", weight: 700 },
		"heading-lg": { brandFont: true, weight: 700 },
		"heading-md": { brandFont: true, weight: 700 },
		"heading-sm": { brandFont: true, weight: 700 },
	},
	"montagu-slab": {},
	"newsreader-plus-jakarta-sans": {},
	nunito: {},
	"oswald-inter": {},
	"oswald-source": {},
	outfit: lightDisplayHeadings,
	"petrona-hanken-grotesk": {},
	"platypi-maven-pro": { "display-lg": { weight: 600 } },
	"playfair-source": {},
	"playpen-sans-grandstander": {},
	"plus-jakarta-sans-inter": {
		"display-lg": { tracking: "-0.025em", weight: 500 },
		"display-md": { tracking: "-0.025em", weight: 500 },
		"display-sm": { tracking: "-0.025em", weight: 500 },
		"heading-lg": { brandFont: true, weight: 500 },
		"heading-md": { brandFont: true, weight: 500 },
		"heading-sm": { brandFont: true, weight: 500 },
	},
	"raleway-lato": {},
	"red-hat-display-source-serif-4": {},
	"rethink-sans-commissioner": {},
	"roboto-serif-dm-sans": lightDisplayHeadings,
	"schibsted-grotesk-noto-serif": {},
	"signika-asap": { "display-lg": { weight: 600 } },
	"sofia-sans-condensed": {},
	"sora-barlow": {},
	"space-grotesk": {},
	"space-grotesk-inter": {
		"display-lg": { weight: 400 },
		"display-md": { weight: 400 },
		"display-sm": { weight: 400 },
	},
	"syne-geist": {},
	"unbounded-geist": {},
	"vollkorn-jost": {},
	"work-sans-rubik": {},
} as const satisfies Record<BrandFontPairingId, BrandTypeScale>;
