const toolNames = [
	"changeLinkPageTheme",
	"recommendBrandAppearance",
	"recommendLinkPageTheme",
	"findStockImage",
	"listContactMessages",
	"triageContactMessage",

	"addWebsiteSection",
	"askUserQuestions",
	"buildWebsite",
	"cancelWebsiteWorkflow",
	"changeWebsiteTemplate",
	"composeWebsiteSection",
	"createContact",
	"createLibraryDocument",
	"deleteContact",
	"editLibraryDocument",
	"editLinkPage",
	"editWebsite",
	"generateLibraryImage",
	"generateWebsite",
	"generateWebsiteLayout",
	"getBrand",
	"getContact",
	"getContactInquirySummary",
	"getDocument",
	"getLibraryAsset",
	"getLinkPage",
	"getWebsiteStatus",
	"inspectTable",
	"inspectWebsite",
	"listBrandOptions",
	"listContacts",
	"listDocuments",
	"listLibraryAssets",
	"listWebsiteTemplates",
	"previewWebsiteTemplate",
	"publishBrand",
	"publishLinkPage",
	"publishWebsite",
	"retrieveKnowledge",
	"updateBrand",
	"updateContact",
	"webSearch",
] as const;

export const getToolLabelKey = (name: string) => toolNames.find((toolName) => toolName === name) ?? "other";
